apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast-cluster
spec:
  serviceName: hazelcast-cluster
  replicas: 3
  selector:
    matchLabels:
      app: hazelcast-cluster
  template:
    metadata:
      labels:
        app: hazelcast-cluster
    spec:
      containers:
        - name: hazelcast-cluster
          image: hazelcast/hazelcast:5.1.2
          ports:
          - containerPort: 5701

---

apiVersion: v1
kind: Service
metadata:
  name: hazelcast-cluster
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: hazelcast-cluster
  ports:
    - name: tcp-hazelcast
      port: 5701
